### ISSUE TITLE
vendor/dragonmantank/cron-expression is missing

### ISSUE THREAD

**Issue by mnederlof** [jstanden/cerb#1233]
It seems the directory is missing, i can find it in vendor/Composer/installed.json, but the folder is missing in the production repository.

The php error that triggered me:
```
2020/03/05 09:44:01 [error] 14517#14517: *10287 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Cron\CronExpression' not found in /var/www/cerb/features/cerberusweb.core/api/events/recurrent/recurrent_behavior.php:100
Stack trace:
#0 /var/www/cerb/features/cerberusweb.core/api/crons/bots.php(52): Event_RecurrentBehavior::getNextOccurrence(Array, 'Europe/Amsterda...')
#1 /var/www/cerb/features/cerberusweb.core/api/crons/bots.php(13): Cron_BotScheduledBehavior->_runRecurrentBehaviors()
#2 /var/www/cerb/api/Extension.class.php(919): Cron_BotScheduledBehavior->run()
#3 /var/www/cerb/features/cerberusweb.core/api/uri/cron.php(134): CerberusCronPageExtension->_run()
#4 /var/www/cerb/libs/devblocks/api/Engine.php(697): ChCronController->handleRequest(Object(DevblocksHttpRequest))
#5 /var/www/cerb/api/Application.class.php(250): DevblocksEngine::processRequest(Object(DevblocksHttpRequest), false)
#6 /var/www/cerb/index.php(114): CerberusApplication::processRequest(Object(DevblocksHttpRequest))
#7 {main}
  thrown in /var/www/cerb/features/cerberusweb.core" while reading response header from upstream, server: cerberus.domain.tld, request: "GET /index.php/cron?loglevel=6 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "cerberus.domain.tld"
```

**Comment by jstanden** [comment]
Hey there! You can pull from `cerb/cerb-release` again for the updated Composer dependencies.

You can also run `composer update --no-dev` in the Cerb directory.
